[package]
name = "gems"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-task = "0.3.18"
parking_lot = "0.11.2"
